### ISSUE TITLE
Проверка пары лог / пасс

### ISSUE THREAD

**Issue by ifkin** [milordixz/AT#11]
Не сделано 8.7 из https://cloud.mail.ru/public/6exk/7ASYfteA1

+

Мне совсем не нравится, что при отправке формы мы уходим со страницы.

Т.е., при клике на "отправить", мы переходим в другой ресурс. Такого не должно происходить. Мы  должны видеть результат авторизации на этой же странице

**Comment by milordixz** [comment]
Сделано! и пожелания учтены

**Comment by ifkin** [comment]
ok
