### ISSUE TITLE
login.equals и password.equals

### ISSUE THREAD

**Issue by ifkin** [milordixz/AT#9]
Зачем нам эти вещи в UsersDAO.checkUser?

Мб просто проверять размер выборки (количество строк, которое вернулось из бд)? Если он == 0 делаем вывод, что логин / пасс кривые.

В противном случае лог / пасс - найдены в бд.

Кстати, стоит учесть что размер выборки может иметь только два состояния: 0 и 1 :)

**Comment by milordixz** [comment]
Исправлено по желанию заказчика

**Comment by ifkin** [comment]
ok
